version = 0.1
[default.deploy.parameters]
stack_name = "get-component-handler-app"
resolve_s3 = true
s3_prefix = "get-component-handler-app"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
